title: Mostafa Saghafi
logo: /assets/img/MS1.png
description: Surface Water, Flood Detection, Climate Change- Remote Sensing- Machine Learning (Python, R)
show_downloads: false
theme: jekyll-theme-minimal
